### ISSUE TITLE
Graph Panel new features

### ISSUE THREAD

**Issue by npechl** [CorpGlory/grafana-graph-panel#9]
I am trying to build a Grafana plugin based on your plugin. 

I would like to add the new features of the graph panel (Time region selection and Rendering a dot when no connecting line can be made). I have added all the necessary files but when i try to use my plugin the following error comes up:

![time region error](https://user-images.githubusercontent.com/44325851/49944107-eb1a3b00-fee9-11e8-9fc4-24d09f3dd052.JPG)

I believe this is because the following file is being imported into `time_region_manager.ts`:

![grafana new features](https://user-images.githubusercontent.com/44325851/49944714-63353080-feeb-11e8-85d9-65569eda4e82.JPG)

If you have any idea what is the right configuration to fix my problem, please let me know!
Any help would be very appreciated!

**Comment by rozetko** [comment]
Hey, @nikopech! It's a known problem with this plugin
Which is fixed in one of our forks: https://github.com/CorpGlory/grafana-multibar-graph-panel by those 2 PRs:
https://github.com/CorpGlory/grafana-multibar-graph-panel/pull/15
https://github.com/CorpGlory/grafana-multibar-graph-panel/pull/17
Which can be applied here with just a couple of changes (related to plugin name)

**Comment by marefr** [comment]
time_region_manager.ts are very similar to threshold_manager.ts. Think you need to change the import like  done in threshold_manager.ts, see [code](https://github.com/CorpGlory/grafana-graph-panel/blob/master/src/threshold_manager.ts#L1).

**Comment by npechl** [comment]
@rozetko @marefr 
Thank you both for the replies. 
Changing the `import` seems to fix the problem.
